<a href="https://colab.research.google.com/github/sneh20122001/Pytorch/blob/main/00_PyTorch_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1. Documentation reading


### 2. Create a random tensor with shape (7, 7).

In [2]:
import torch

random_tensor = torch.rand(7,7)
random_tensor

tensor([[0.6616, 0.6913, 0.7975, 0.4473, 0.9056, 0.4596, 0.0989],
        [0.5676, 0.2281, 0.7289, 0.0351, 0.3880, 0.5275, 0.5022],
        [0.1974, 0.5998, 0.6812, 0.4524, 0.5837, 0.9762, 0.1611],
        [0.2435, 0.6184, 0.2623, 0.3030, 0.5076, 0.7981, 0.3665],
        [0.7856, 0.3119, 0.4611, 0.5233, 0.0548, 0.7287, 0.3292],
        [0.8237, 0.4716, 0.1000, 0.4733, 0.1310, 0.6519, 0.6054],
        [0.2731, 0.8793, 0.7988, 0.4125, 0.1561, 0.2953, 0.7137]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [5]:
random_tensor2 = torch.rand(1,7)
random_tensor2.T

torch.matmul(random_tensor,random_tensor2.T)


tensor([[1.4375],
        [1.8735],
        [1.4807],
        [1.5930],
        [1.7396],
        [1.2391],
        [1.7917]])

### 4. Set the random seed to 0 and do 2 & 3 over again.

In [41]:
torch.manual_seed(0)

random_tensor_A = torch.rand(7,7)
random_tensor_B = torch.rand(1,7)

torch.matmul(random_tensor_A,random_tensor_B.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [42]:
torch.cuda.manual_seed(1234)


6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [5]:
torch.manual_seed(1234)

A = torch.rand(2,3)
B = torch.rand(3,2)

device = 'cuda' if torch.cuda.is_available() else "cpu"
print(device)

A1 = A.to(device)
B2 = B.to(device)

print(A1)
print(B2)

cuda
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]], device='cuda:0')
tensor([[0.0518, 0.4681],
        [0.6738, 0.3315],
        [0.7837, 0.5631]], device='cuda:0')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [19]:
X = torch.matmul(A1,B2)
X,X.shape

(tensor([[0.4759, 0.2931],
         [0.6074, 0.5855]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [20]:
X.min()

tensor(0.2931, device='cuda:0')

In [21]:
X.max()

tensor(0.6074, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [22]:
X.argmax()

tensor(2, device='cuda:0')

In [23]:
X.argmin()

tensor(1, device='cuda:0')

### 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [46]:
torch.manual_seed(7)

X = torch.rand(size=(1,1,1,10))
print(X, X.size())

Y = X.squeeze()

print(Y, Y.size())

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
