<a href="https://colab.research.google.com/github/sneh20122001/Pytorch/blob/main/00_Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals

## What is PyTorch?

PyTorch is an open source machine learning and deep learning framework.

## What can PyTorch be used for?

PyTorch allows you to manipulate and process data and write machine learning algorithms using Python code.

## Who uses PyTorch?

Many of the worlds largest technology companies such as Meta (Facebook), Tesla and Microsoft as well as artificial intelligence research companies such as [OpenAI use PyTorch] to power research and bring machine learning to their products.



## Importing PyTorch

In [1]:
import torch
print(torch.__version__)

2.1.0+cu121


## Introduction to tensors


Tensors are the fundamental building block of machine learning.

Their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape `[3, 224, 224]` which would mean `[colour_channels, height, width]`, as in the image has `3` colour channels (red, green, blue), a height of `224` pixels and a width of `224` pixels.

![example of going from an input image to a tensor representation of the image, image gets broken down into 3 colour channels as well as numbers to represent the height and width](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-tensor-shape-example-of-image.png)




### Creating tensors



The first thing we're going to create is a **scalar**.

A scalar is a single number and in tensor-speak it's a zero dimension tensor.



In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# dimensions of a tensor
scalar.ndim

0

In [4]:
# Get the Python number within a tensor (only works with one-element tensors)
scalar.item()

7

In [5]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
# Check shape of vector
vector.shape

torch.Size([2])

In [8]:
# Matrix
MATRIX = torch.tensor(
    [
        [7,8],[5,6]
    ]
)
MATRIX

tensor([[7, 8],
        [5, 6]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
# Get value from the index value
MATRIX[1]

tensor([5, 6])

In [12]:
# TENSOR
TENSOR = torch.tensor(
    [
        [
            [1,2,3],
            [4,5,6],
            [7,8,9]
        ]
    ]
)
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape


torch.Size([1, 3, 3])

In [15]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [16]:
# exercise
TENSOR1 = torch.tensor([[[
    [
        [1,2,3],
        [2,3,4],
        [3,4,5]
    ],
    [
        [4,5,6],
        [5,6,7],
        [7,8,9]
    ]
]]])
TENSOR1

tensor([[[[[1, 2, 3],
           [2, 3, 4],
           [3, 4, 5]],

          [[4, 5, 6],
           [5, 6, 7],
           [7, 8, 9]]]]])

In [17]:
TENSOR1.ndim

5

In [18]:
TENSOR1.shape

torch.Size([1, 1, 2, 3, 3])

### Random Tensors


why random tensors??

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...`

In [19]:
# Create a random tensor of size (3, 4)
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.2722, 0.4835, 0.4409, 0.1323],
         [0.2034, 0.9227, 0.8706, 0.8771],
         [0.0134, 0.4632, 0.3185, 0.2763]]),
 torch.float32)

In [20]:
random_tensor.ndim

2

In [21]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # Height,Width,Colour Channels (R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [24]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [25]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

### Creating a range of tensors and tensors-like

In [26]:
# use torch.arange()
one_to_ten=torch.arange(1,11,1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [28]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # what data type
                               device=None,
                               requires_grad=False # gradients
                               )
float_32_tensor

tensor([3., 6., 9.])

In [29]:
float_32_tensor.dtype

torch.float32

In [30]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [31]:
float_32_tensor * float_16_tensor

tensor([ 9., 36., 81.])

In [32]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [33]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

In [34]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.4113, 0.9979, 0.3268, 0.3058],
        [0.7947, 0.4878, 0.5426, 0.8322],
        [0.4913, 0.5407, 0.0709, 0.2997]])

In [35]:
some_tensor.shape

torch.Size([3, 4])

In [36]:
some_tensor.size()

torch.Size([3, 4])

In [37]:
# find out details about some tensor
print(some_tensor)
print(f"datatype of tensor: { some_tensor.dtype}")
print(f"shape of tensor: { some_tensor.shape}")
print(f"Device of tensor: { some_tensor.device}")

tensor([[0.4113, 0.9979, 0.3268, 0.3058],
        [0.7947, 0.4878, 0.5426, 0.8322],
        [0.4913, 0.5407, 0.0709, 0.2997]])
datatype of tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)


In [38]:
# Create a tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [39]:
# multiply
tensor * 100

tensor([100, 200, 300])

In [40]:
tensor - 10

tensor([-9, -8, -7])

In [41]:
# try out pytorch in-built functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [42]:
torch.add(tensor,10)

tensor([11, 12, 13])

### Matrix multiplication

two way:

1. Matrix multiplication(dot product)

2. element-wise multiplication

In [43]:
# element-wise multiplication
print(tensor)
tensor * tensor

tensor([1, 2, 3])


tensor([1, 4, 9])

In [44]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [45]:
tensor

tensor([1, 2, 3])

In [46]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [47]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] + tensor[i]
print(value)

tensor(12)
CPU times: user 2.26 ms, sys: 36 µs, total: 2.29 ms
Wall time: 2.97 ms


In [48]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 509 µs, sys: 0 ns, total: 509 µs
Wall time: 825 µs


tensor(14)

### One of the most common error in DL and ML is shape error

(3,4) @ (3,4) -> it's not work


(2,3) @ (3,4) -> it's work -> (2,4)



In [49]:
torch.matmul(torch.rand(3,3), torch.rand(3,2))

tensor([[0.9032, 0.3519],
        [0.9347, 0.5555],
        [0.6506, 0.4617]])

In [50]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([
    [1,2],
    [3,4],
    [5,6]
])
tensor_B = torch.tensor([
    [7,10],
    [8,11],
    [9,12]
])

torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [51]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [52]:
# to fix tensor shape issues using transpose
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [53]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

### Tensor aggregation

In [54]:
# Create a tensor
x = torch.arange(1,100,10)
x,x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [55]:
# find the min
torch.min(x),x.min()

(tensor(1), tensor(1))

In [56]:
# find the max
torch.max(x),x.max()

(tensor(91), tensor(91))

In [57]:
# find the mean
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [58]:
# find the sum
torch.sum(x),x.sum()

(tensor(460), tensor(460))

### Finding the position of min and max

In [60]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [61]:
# find the minimum value
x.argmin()

tensor(0)

In [62]:
x[1]

tensor(11)

In [63]:
# find the maximum value
x.argmax()

tensor(9)

### Reshaping,stacking,squeezing and unsqueeing tensors




In [64]:
x = torch.arange(1.,8.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [65]:
# add extra dimension
x_reshaped = x.reshape(1,7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [67]:
# change the view
z = x.view(1,7)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [68]:
# z also change original x
z[:,0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

In [69]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [70]:
# torch.squeeze -> remove single dimensions from tensor
x_squeezed=x_reshaped.squeeze()

In [71]:
x_reshaped.squeeze().shape

torch.Size([7])

In [72]:
# torch.unsqueeze() -> add one dimensions
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed

tensor([[5., 2., 3., 4., 5., 6., 7.]])

In [73]:
# torch.permute -> rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # H,W,COLOUR

# permute the original tensor to rearange the axis order
x_permuted = x_original.permute(2,0,1) # shift 0->1,1->2,2->0
x_permuted.shape

torch.Size([3, 224, 224])

### Indexing(selecting data from tensors)


Indexing with PyTorch is similar to indexing with numpy

In [77]:
x = torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [78]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
x[0][0]

tensor([1, 2, 3])

In [80]:
x[0][1][1]

tensor(5)

In [81]:
x[0][2][2]

tensor(9)

In [82]:
x[0,2,2]

tensor(9)

In [83]:
x[:,:,1]

tensor([[2, 5, 8]])

In [84]:
x[:,1:,0]

tensor([[4, 7]])

In [85]:
x[0,:,2]

tensor([3, 6, 9])

### Pytorch tensors & Numpy



In [86]:
import numpy as np

array = np.arange(1.,8.)
tensor = torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
array.dtype

dtype('float64')

In [88]:
torch.arange(1.0,8.0).dtype

torch.float32

In [89]:
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [90]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [91]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducbility (trying to take random out of random)

``start with random numbers -> tensor operations -> try to make better (again and again and again)``

In [39]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0922, 0.3409, 0.0183, 0.3574],
        [0.5424, 0.6816, 0.8611, 0.1339],
        [0.4774, 0.0451, 0.3822, 0.3438]])
tensor([[0.1586, 0.0548, 0.6108, 0.3531],
        [0.9612, 0.5231, 0.2612, 0.0051],
        [0.2503, 0.0043, 0.6675, 0.2196]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [42]:
# created two random tensors with the same values -> seed


RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)



print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
